# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mypc/Dionysus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mypc/Dionysus/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/mypc/Dionysus/build && $(CMAKE_COMMAND) -E cmake_progress_start /home/mypc/Dionysus/build/CMakeFiles /home/mypc/Dionysus/build/bindings/python/CMakeFiles/progress.marks
	cd /home/mypc/Dionysus/build && $(MAKE) -f CMakeFiles/Makefile2 bindings/python/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mypc/Dionysus/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/mypc/Dionysus/build && $(MAKE) -f CMakeFiles/Makefile2 bindings/python/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/mypc/Dionysus/build && $(MAKE) -f CMakeFiles/Makefile2 bindings/python/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/mypc/Dionysus/build && $(MAKE) -f CMakeFiles/Makefile2 bindings/python/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/mypc/Dionysus/build && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
bindings/python/CMakeFiles/_dionysus.dir/rule:
	cd /home/mypc/Dionysus/build && $(MAKE) -f CMakeFiles/Makefile2 bindings/python/CMakeFiles/_dionysus.dir/rule
.PHONY : bindings/python/CMakeFiles/_dionysus.dir/rule

# Convenience name for target.
_dionysus: bindings/python/CMakeFiles/_dionysus.dir/rule
.PHONY : _dionysus

# fast build rule for target.
_dionysus/fast:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/build
.PHONY : _dionysus/fast

# Convenience name for target.
bindings/python/CMakeFiles/dionysus.dir/rule:
	cd /home/mypc/Dionysus/build && $(MAKE) -f CMakeFiles/Makefile2 bindings/python/CMakeFiles/dionysus.dir/rule
.PHONY : bindings/python/CMakeFiles/dionysus.dir/rule

# Convenience name for target.
dionysus: bindings/python/CMakeFiles/dionysus.dir/rule
.PHONY : dionysus

# fast build rule for target.
dionysus/fast:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/dionysus.dir/build.make bindings/python/CMakeFiles/dionysus.dir/build
.PHONY : dionysus/fast

# Convenience name for target.
bindings/python/CMakeFiles/dionysus-link.dir/rule:
	cd /home/mypc/Dionysus/build && $(MAKE) -f CMakeFiles/Makefile2 bindings/python/CMakeFiles/dionysus-link.dir/rule
.PHONY : bindings/python/CMakeFiles/dionysus-link.dir/rule

# Convenience name for target.
dionysus-link: bindings/python/CMakeFiles/dionysus-link.dir/rule
.PHONY : dionysus-link

# fast build rule for target.
dionysus-link/fast:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/dionysus-link.dir/build.make bindings/python/CMakeFiles/dionysus-link.dir/build
.PHONY : dionysus-link/fast

# target to build an object file
alphashapes2d.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/alphashapes2d.o
.PHONY : alphashapes2d.o

# target to preprocess a source file
alphashapes2d.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/alphashapes2d.i
.PHONY : alphashapes2d.i

# target to generate assembly for a file
alphashapes2d.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/alphashapes2d.s
.PHONY : alphashapes2d.s

# target to build an object file
alphashapes3d.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/alphashapes3d.o
.PHONY : alphashapes3d.o

# target to preprocess a source file
alphashapes3d.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/alphashapes3d.i
.PHONY : alphashapes3d.i

# target to generate assembly for a file
alphashapes3d.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/alphashapes3d.s
.PHONY : alphashapes3d.s

# target to build an object file
birthid.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/birthid.o
.PHONY : birthid.o

# target to preprocess a source file
birthid.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/birthid.i
.PHONY : birthid.i

# target to generate assembly for a file
birthid.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/birthid.s
.PHONY : birthid.s

# target to build an object file
chain.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/chain.o
.PHONY : chain.o

# target to preprocess a source file
chain.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/chain.i
.PHONY : chain.i

# target to generate assembly for a file
chain.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/chain.s
.PHONY : chain.s

# target to build an object file
cohomology-persistence.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/cohomology-persistence.o
.PHONY : cohomology-persistence.o

# target to preprocess a source file
cohomology-persistence.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/cohomology-persistence.i
.PHONY : cohomology-persistence.i

# target to generate assembly for a file
cohomology-persistence.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/cohomology-persistence.s
.PHONY : cohomology-persistence.s

# target to build an object file
dionysus.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/dionysus.o
.PHONY : dionysus.o

# target to preprocess a source file
dionysus.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/dionysus.i
.PHONY : dionysus.i

# target to generate assembly for a file
dionysus.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/dionysus.s
.PHONY : dionysus.s

# target to build an object file
distances.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/distances.o
.PHONY : distances.o

# target to preprocess a source file
distances.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/distances.i
.PHONY : distances.i

# target to generate assembly for a file
distances.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/distances.s
.PHONY : distances.s

# target to build an object file
dynamic-persistence.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/dynamic-persistence.o
.PHONY : dynamic-persistence.o

# target to preprocess a source file
dynamic-persistence.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/dynamic-persistence.i
.PHONY : dynamic-persistence.i

# target to generate assembly for a file
dynamic-persistence.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/dynamic-persistence.s
.PHONY : dynamic-persistence.s

# target to build an object file
filtration.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/filtration.o
.PHONY : filtration.o

# target to preprocess a source file
filtration.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/filtration.i
.PHONY : filtration.i

# target to generate assembly for a file
filtration.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/filtration.s
.PHONY : filtration.s

# target to build an object file
persistence-diagram.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/persistence-diagram.o
.PHONY : persistence-diagram.o

# target to preprocess a source file
persistence-diagram.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/persistence-diagram.i
.PHONY : persistence-diagram.i

# target to generate assembly for a file
persistence-diagram.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/persistence-diagram.s
.PHONY : persistence-diagram.s

# target to build an object file
rips.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/rips.o
.PHONY : rips.o

# target to preprocess a source file
rips.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/rips.i
.PHONY : rips.i

# target to generate assembly for a file
rips.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/rips.s
.PHONY : rips.s

# target to build an object file
simplex.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/simplex.o
.PHONY : simplex.o

# target to preprocess a source file
simplex.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/simplex.i
.PHONY : simplex.i

# target to generate assembly for a file
simplex.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/simplex.s
.PHONY : simplex.s

# target to build an object file
static-persistence.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/static-persistence.o
.PHONY : static-persistence.o

# target to preprocess a source file
static-persistence.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/static-persistence.i
.PHONY : static-persistence.i

# target to generate assembly for a file
static-persistence.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/static-persistence.s
.PHONY : static-persistence.s

# target to build an object file
zigzag-persistence.o:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/zigzag-persistence.o
.PHONY : zigzag-persistence.o

# target to preprocess a source file
zigzag-persistence.i:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/zigzag-persistence.i
.PHONY : zigzag-persistence.i

# target to generate assembly for a file
zigzag-persistence.s:
	cd /home/mypc/Dionysus/build && $(MAKE) -f bindings/python/CMakeFiles/_dionysus.dir/build.make bindings/python/CMakeFiles/_dionysus.dir/zigzag-persistence.s
.PHONY : zigzag-persistence.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... _dionysus"
	@echo "... dionysus"
	@echo "... dionysus-link"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... alphashapes2d.o"
	@echo "... alphashapes2d.i"
	@echo "... alphashapes2d.s"
	@echo "... alphashapes3d.o"
	@echo "... alphashapes3d.i"
	@echo "... alphashapes3d.s"
	@echo "... birthid.o"
	@echo "... birthid.i"
	@echo "... birthid.s"
	@echo "... chain.o"
	@echo "... chain.i"
	@echo "... chain.s"
	@echo "... cohomology-persistence.o"
	@echo "... cohomology-persistence.i"
	@echo "... cohomology-persistence.s"
	@echo "... dionysus.o"
	@echo "... dionysus.i"
	@echo "... dionysus.s"
	@echo "... distances.o"
	@echo "... distances.i"
	@echo "... distances.s"
	@echo "... dynamic-persistence.o"
	@echo "... dynamic-persistence.i"
	@echo "... dynamic-persistence.s"
	@echo "... filtration.o"
	@echo "... filtration.i"
	@echo "... filtration.s"
	@echo "... persistence-diagram.o"
	@echo "... persistence-diagram.i"
	@echo "... persistence-diagram.s"
	@echo "... rips.o"
	@echo "... rips.i"
	@echo "... rips.s"
	@echo "... simplex.o"
	@echo "... simplex.i"
	@echo "... simplex.s"
	@echo "... static-persistence.o"
	@echo "... static-persistence.i"
	@echo "... static-persistence.s"
	@echo "... zigzag-persistence.o"
	@echo "... zigzag-persistence.i"
	@echo "... zigzag-persistence.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/mypc/Dionysus/build && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

